version: "3"
services:
  annotation-postgres:
    image: postgres:15.2
    container_name: annotation-postgres
    volumes:
      - annotation-data:/var/lib/postgresql/data
      - ./annotation-app/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=annotation
      - POSTGRES_USER=annotation
      - POSTGRES_PASSWORD=annotation

  annotation-app:
    build: ./annotation-app
    container_name: annotation-app
    environment:
      - POSTGRES_DB=annotation
      - POSTGRES_USER=annotation
      - POSTGRES_PASSWORD=annotation
      - POSTGRES_HOST=annotation-postgres
    ports:
      - 8080:8080
    links:
      - annotation-postgres
    entrypoint: ["bash", "-c", "sed -i 's/localhost/annotation-postgres/g' alembic.ini && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8080"]
    depends_on:
      - annotation-postgres

  annotation-ui:
    build: ./annotation-ui
    container_name: annotation-ui
    ports:
      - 80:80
    links:
      - annotation-app
    depends_on:
      - annotation-app

volumes:
  annotation-data:
